#############################################################################
# Makefile for building: Example
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Dec 30 16:02:53 2013
# Project:  Example.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Example.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/phonon -I/usr/include/qt4 -I/usr/include/qt4/phonon_compat -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lphonon -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		Table.cpp \
		Croupier.cpp \
		Player.cpp \
		Card.cpp \
		Participant.cpp \
		Box.cpp \
		GameThread.cpp \
		dragwidget.cpp \
		mylabel.cpp \
		ClickableLabel.cpp moc_mainwindow.cpp \
		moc_Croupier.cpp \
		moc_Player.cpp \
		moc_Participant.cpp \
		moc_Box.cpp \
		moc_GameThread.cpp \
		moc_dragwidget.cpp \
		moc_mylabel.cpp \
		moc_ClickableLabel.cpp \
		qrc_Blackjack.cpp
OBJECTS       = main.o \
		mainwindow.o \
		Table.o \
		Croupier.o \
		Player.o \
		Card.o \
		Participant.o \
		Box.o \
		GameThread.o \
		dragwidget.o \
		mylabel.o \
		ClickableLabel.o \
		moc_mainwindow.o \
		moc_Croupier.o \
		moc_Player.o \
		moc_Participant.o \
		moc_Box.o \
		moc_GameThread.o \
		moc_dragwidget.o \
		moc_mylabel.o \
		moc_ClickableLabel.o \
		qrc_Blackjack.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Example.pro
QMAKE_TARGET  = Example
DESTDIR       = 
TARGET        = Example

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Example.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Example.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Example.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Example1.0.0 || $(MKDIR) .tmp/Example1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Example1.0.0/ && $(COPY_FILE) --parents mainwindow.h Table.hpp Croupier.hpp Player.hpp Card.hpp Participant.hpp Box.hpp GameThread.hpp dragwidget.h mylabel.h ClickableLabel.hpp .tmp/Example1.0.0/ && $(COPY_FILE) --parents Blackjack.qrc .tmp/Example1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp Table.cpp Croupier.cpp Player.cpp Card.cpp Participant.cpp Box.cpp GameThread.cpp dragwidget.cpp mylabel.cpp ClickableLabel.cpp .tmp/Example1.0.0/ && (cd `dirname .tmp/Example1.0.0` && $(TAR) Example1.0.0.tar Example1.0.0 && $(COMPRESS) Example1.0.0.tar) && $(MOVE) `dirname .tmp/Example1.0.0`/Example1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Example1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_Croupier.cpp moc_Player.cpp moc_Participant.cpp moc_Box.cpp moc_GameThread.cpp moc_dragwidget.cpp moc_mylabel.cpp moc_ClickableLabel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_Croupier.cpp moc_Player.cpp moc_Participant.cpp moc_Box.cpp moc_GameThread.cpp moc_dragwidget.cpp moc_mylabel.cpp moc_ClickableLabel.cpp
moc_mainwindow.cpp: Table.hpp \
		Box.hpp \
		Player.hpp \
		Card.hpp \
		Participant.hpp \
		Croupier.hpp \
		GameThread.hpp \
		ClickableLabel.hpp \
		dragwidget.h \
		mylabel.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_Croupier.cpp: Participant.hpp \
		Card.hpp \
		Croupier.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Croupier.hpp -o moc_Croupier.cpp

moc_Player.cpp: Player.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Player.hpp -o moc_Player.cpp

moc_Participant.cpp: Card.hpp \
		Participant.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Participant.hpp -o moc_Participant.cpp

moc_Box.cpp: Player.hpp \
		Card.hpp \
		Participant.hpp \
		Box.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Box.hpp -o moc_Box.cpp

moc_GameThread.cpp: Table.hpp \
		Box.hpp \
		Player.hpp \
		Card.hpp \
		Participant.hpp \
		Croupier.hpp \
		GameThread.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GameThread.hpp -o moc_GameThread.cpp

moc_dragwidget.cpp: mylabel.h \
		dragwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dragwidget.h -o moc_dragwidget.cpp

moc_mylabel.cpp: mylabel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mylabel.h -o moc_mylabel.cpp

moc_ClickableLabel.cpp: ClickableLabel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ClickableLabel.hpp -o moc_ClickableLabel.cpp

compiler_rcc_make_all: qrc_Blackjack.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Blackjack.cpp
qrc_Blackjack.cpp: Blackjack.qrc \
		StatusBubble.png \
		Background3.png \
		DoubleButtonSmall.png \
		SplitButtonSmall.png \
		NoButtonSmall.png \
		StackSpot.png \
		Bet_Ring2.gif \
		Background.png \
		HandValueSpot.png \
		Background4.png \
		ResultsSummary.png \
		DoneRedButtonSmall.png \
		HitButtonSmall.png \
		BlackjackText.gif \
		Background.jpg \
		SurrenderButtonSmall.png \
		StandButtonSmall.png \
		Background2.png \
		DoneGreenButtonSmall.png \
		BustText.gif \
		YesButtonSmall.png
	/usr/bin/rcc -name Blackjack Blackjack.qrc -o qrc_Blackjack.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		Table.hpp \
		Box.hpp \
		Player.hpp \
		Card.hpp \
		Participant.hpp \
		Croupier.hpp \
		GameThread.hpp \
		ClickableLabel.hpp \
		dragwidget.h \
		mylabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		Table.hpp \
		Box.hpp \
		Player.hpp \
		Card.hpp \
		Participant.hpp \
		Croupier.hpp \
		GameThread.hpp \
		ClickableLabel.hpp \
		dragwidget.h \
		mylabel.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

Table.o: Table.cpp Table.hpp \
		Box.hpp \
		Player.hpp \
		Card.hpp \
		Participant.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Table.o Table.cpp

Croupier.o: Croupier.cpp Croupier.hpp \
		Participant.hpp \
		Card.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Croupier.o Croupier.cpp

Player.o: Player.cpp Player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

Card.o: Card.cpp Card.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Card.o Card.cpp

Participant.o: Participant.cpp Participant.hpp \
		Card.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Participant.o Participant.cpp

Box.o: Box.cpp Box.hpp \
		Player.hpp \
		Card.hpp \
		Participant.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Box.o Box.cpp

GameThread.o: GameThread.cpp GameThread.hpp \
		Table.hpp \
		Box.hpp \
		Player.hpp \
		Card.hpp \
		Participant.hpp \
		Croupier.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameThread.o GameThread.cpp

dragwidget.o: dragwidget.cpp dragwidget.h \
		mylabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dragwidget.o dragwidget.cpp

mylabel.o: mylabel.cpp mylabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylabel.o mylabel.cpp

ClickableLabel.o: ClickableLabel.cpp ClickableLabel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClickableLabel.o ClickableLabel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_Croupier.o: moc_Croupier.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Croupier.o moc_Croupier.cpp

moc_Player.o: moc_Player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Player.o moc_Player.cpp

moc_Participant.o: moc_Participant.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Participant.o moc_Participant.cpp

moc_Box.o: moc_Box.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Box.o moc_Box.cpp

moc_GameThread.o: moc_GameThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameThread.o moc_GameThread.cpp

moc_dragwidget.o: moc_dragwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dragwidget.o moc_dragwidget.cpp

moc_mylabel.o: moc_mylabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mylabel.o moc_mylabel.cpp

moc_ClickableLabel.o: moc_ClickableLabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClickableLabel.o moc_ClickableLabel.cpp

qrc_Blackjack.o: qrc_Blackjack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Blackjack.o qrc_Blackjack.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

